apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: insighthub-api
  namespace: insighthub
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  namespaceSelector:
    matchNames:
      - insighthub
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
